name: Terraform Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Account number (e.g., 1, 2, 3)'
        required: true
      module:
        description: 'Module name (e.g., some module)'
        required: true
env:
      AWS_REGION: 'us-west-2'
      TF_VERSION: '1.4.0'
      
permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Navigate to the Correct Module Directory
        run: |
          MODULE_PATH="account-${{ github.event.inputs.account }}/${{ github.event.inputs.module }}"
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV
          if [ ! -d "$MODULE_PATH" ]; then
            echo "Error: Directory $MODULE_PATH does not exist!"
            exit 1
          fi

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.MODULE_PATH }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.MODULE_PATH }}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.MODULE_PATH }}