name: Terraform Sync

on:
  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  TF_VERSION: '1.4.0'

jobs:
  detect-paths:
    runs-on: ubuntu-latest
    outputs:
      detected_paths: ${{ steps.detect.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect folders
        id: detect
        run: |
          # Get the list of subdirectories
          FOLDERS=($(find . -type d -path './account*/*'))

          # Convert array to JSON-like format
          echo "folders=[\"${FOLDERS[@]}\"]" | sed 's/ /", "/g' >> $GITHUB_OUTPUT
          
  terraform:
    runs-on: ubuntu-latest
    needs: detect-paths
    strategy:
      matrix:
        folders: ${{ fromJson(needs.detect-paths.outputs.detected_paths) }}  # Parse as an array

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # Set your Terraform version here

      - name: Terraform Init and Plan and Deploy
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: ${{ matrix.folders }}
